
// -*- C++ -*-
// This is file was automatically generated by $DAnCE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 3
#define DAnCE_MICRO_VERSION 6
#define DAnCE_VERSION "1.3.6"
#define DAnCE_VERSION_CODE 66310
#define DAnCE_MAKE_VERSION_CODE(a,b,c) (((a) << 16) + ((b) << 8) + (c))
