/*
 * This code was generated by the XML Schema Compiler.
 *
 * Changes made to this code will most likely be overwritten
 * when the handlers are recompiled.
 *
 * If you find errors or feel that there are bugfixes to be made,
 * please report this to the XSC project at
 * https://github.com/DOCGroup/XSC
 */
#ifndef CDD_HPP
#define CDD_HPP

#include "XSC_XML_Handlers_Export.h"
// Forward declarations.
namespace DAnCE
{
  namespace Config_Handlers
  {
    class Domain;
    class Bridge;
    class Interconnect;
    class Node;
    class SharedResource;
  }
}

#include <memory>
#include <string>
#include <list>
#include "ace/XML_Utils/XMLSchema/Types.hpp"
#include "ace/XML_Utils/XMLSchema/id_map.hpp"
#include "ace/Refcounted_Auto_Ptr.h"
#include "ace/Null_Mutex.h"
#include "ace/TSS_T.h"
#include "ace/ace_wchar.h"
#include "ace/Singleton.h"

#include "Basic_Deployment_Data.hpp"

namespace DAnCE
{
  namespace Config_Handlers
  {
    class XSC_XML_Handlers_Export Domain : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Domain, ACE_Null_Mutex> _ptr;

      // UUID
      public:
      bool UUID_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& UUID () const;
      void UUID (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > UUID_auto_ptr_type;
      UUID_auto_ptr_type UUID_;

      // label
      public:
      bool label_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& label () const;
      void label (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > label_auto_ptr_type;
      label_auto_ptr_type label_;

      // node
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Node, ACE_Null_Mutex> node_value_type;
      typedef std::list<node_value_type> node_container_type;
      typedef node_container_type::iterator node_iterator;
      typedef node_container_type::const_iterator node_const_iterator;
      node_iterator begin_node ();
      node_iterator end_node ();
      node_const_iterator begin_node () const;
      node_const_iterator end_node () const;
      void add_node (node_value_type const&);
      size_t count_node () const;

      protected:
      node_container_type node_;

      // interconnect
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Interconnect, ACE_Null_Mutex> interconnect_value_type;
      typedef std::list<interconnect_value_type> interconnect_container_type;
      typedef interconnect_container_type::iterator interconnect_iterator;
      typedef interconnect_container_type::const_iterator interconnect_const_iterator;
      interconnect_iterator begin_interconnect ();
      interconnect_iterator end_interconnect ();
      interconnect_const_iterator begin_interconnect () const;
      interconnect_const_iterator end_interconnect () const;
      void add_interconnect (interconnect_value_type const&);
      size_t count_interconnect () const;

      protected:
      interconnect_container_type interconnect_;

      // bridge
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Bridge, ACE_Null_Mutex> bridge_value_type;
      typedef std::list<bridge_value_type> bridge_container_type;
      typedef bridge_container_type::iterator bridge_iterator;
      typedef bridge_container_type::const_iterator bridge_const_iterator;
      bridge_iterator begin_bridge ();
      bridge_iterator end_bridge ();
      bridge_const_iterator begin_bridge () const;
      bridge_const_iterator end_bridge () const;
      void add_bridge (bridge_value_type const&);
      size_t count_bridge () const;

      protected:
      bridge_container_type bridge_;

      // sharedResource
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::SharedResource, ACE_Null_Mutex> sharedResource_value_type;
      typedef std::list<sharedResource_value_type> sharedResource_container_type;
      typedef sharedResource_container_type::iterator sharedResource_iterator;
      typedef sharedResource_container_type::const_iterator sharedResource_const_iterator;
      sharedResource_iterator begin_sharedResource ();
      sharedResource_iterator end_sharedResource ();
      sharedResource_const_iterator begin_sharedResource () const;
      sharedResource_const_iterator end_sharedResource () const;
      void add_sharedResource (sharedResource_value_type const&);
      size_t count_sharedResource () const;

      protected:
      sharedResource_container_type sharedResource_;

      // infoProperty
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Property, ACE_Null_Mutex> infoProperty_value_type;
      typedef std::list<infoProperty_value_type> infoProperty_container_type;
      typedef infoProperty_container_type::iterator infoProperty_iterator;
      typedef infoProperty_container_type::const_iterator infoProperty_const_iterator;
      infoProperty_iterator begin_infoProperty ();
      infoProperty_iterator end_infoProperty ();
      infoProperty_const_iterator begin_infoProperty () const;
      infoProperty_const_iterator end_infoProperty () const;
      void add_infoProperty (infoProperty_value_type const&);
      size_t count_infoProperty () const;

      protected:
      infoProperty_container_type infoProperty_;

      public:
      Domain (node_container_type const& node__);

      explicit Domain (::XSCRT::XML::Element<ACE_TCHAR> const&);
      Domain (Domain const& s);
      Domain& operator= (Domain const& s);

      private:
      char regulator__;
    };


    class XSC_XML_Handlers_Export Bridge : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Bridge, ACE_Null_Mutex> _ptr;

      // name
      public:
      ::XMLSchema::string<ACE_TCHAR> const& name () const;
      void name (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > name_auto_ptr_type;
      name_auto_ptr_type name_;

      // label
      public:
      bool label_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& label () const;
      void label (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > label_auto_ptr_type;
      label_auto_ptr_type label_;

      // connect
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Interconnect, ACE_Null_Mutex> connect_value_type;
      typedef std::list<connect_value_type> connect_container_type;
      typedef connect_container_type::iterator connect_iterator;
      typedef connect_container_type::const_iterator connect_const_iterator;
      connect_iterator begin_connect ();
      connect_iterator end_connect ();
      connect_const_iterator begin_connect () const;
      connect_const_iterator end_connect () const;
      void add_connect (connect_value_type const&);
      size_t count_connect () const;

      protected:
      connect_container_type connect_;

      // resource
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Resource, ACE_Null_Mutex> resource_value_type;
      typedef std::list<resource_value_type> resource_container_type;
      typedef resource_container_type::iterator resource_iterator;
      typedef resource_container_type::const_iterator resource_const_iterator;
      resource_iterator begin_resource ();
      resource_iterator end_resource ();
      resource_const_iterator begin_resource () const;
      resource_const_iterator end_resource () const;
      void add_resource (resource_value_type const&);
      size_t count_resource () const;

      protected:
      resource_container_type resource_;

      public:
      Bridge (::XMLSchema::string<ACE_TCHAR> const& name__,
              connect_container_type const& connect__);

      explicit Bridge (::XSCRT::XML::Element<ACE_TCHAR> const&);
      Bridge (Bridge const& s);
      Bridge& operator= (Bridge const& s);

      private:
      char regulator__;
    };


    class XSC_XML_Handlers_Export Interconnect : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Interconnect, ACE_Null_Mutex> _ptr;

      // name
      public:
      ::XMLSchema::string<ACE_TCHAR> const& name () const;
      void name (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > name_auto_ptr_type;
      name_auto_ptr_type name_;

      // label
      public:
      bool label_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& label () const;
      void label (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > label_auto_ptr_type;
      label_auto_ptr_type label_;

      // connection
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Bridge, ACE_Null_Mutex> connection_value_type;
      typedef std::list<connection_value_type> connection_container_type;
      typedef connection_container_type::iterator connection_iterator;
      typedef connection_container_type::const_iterator connection_const_iterator;
      connection_iterator begin_connection ();
      connection_iterator end_connection ();
      connection_const_iterator begin_connection () const;
      connection_const_iterator end_connection () const;
      void add_connection (connection_value_type const&);
      size_t count_connection () const;

      protected:
      connection_container_type connection_;

      // connect
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Node, ACE_Null_Mutex> connect_value_type;
      typedef std::list<connect_value_type> connect_container_type;
      typedef connect_container_type::iterator connect_iterator;
      typedef connect_container_type::const_iterator connect_const_iterator;
      connect_iterator begin_connect ();
      connect_iterator end_connect ();
      connect_const_iterator begin_connect () const;
      connect_const_iterator end_connect () const;
      void add_connect (connect_value_type const&);
      size_t count_connect () const;

      protected:
      connect_container_type connect_;

      // resource
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Resource, ACE_Null_Mutex> resource_value_type;
      typedef std::list<resource_value_type> resource_container_type;
      typedef resource_container_type::iterator resource_iterator;
      typedef resource_container_type::const_iterator resource_const_iterator;
      resource_iterator begin_resource ();
      resource_iterator end_resource ();
      resource_const_iterator begin_resource () const;
      resource_const_iterator end_resource () const;
      void add_resource (resource_value_type const&);
      size_t count_resource () const;

      protected:
      resource_container_type resource_;

      public:
      Interconnect (::XMLSchema::string<ACE_TCHAR> const& name__,
                    connect_container_type const& connect__);

      explicit Interconnect (::XSCRT::XML::Element<ACE_TCHAR> const&);
      Interconnect (Interconnect const& s);
      Interconnect& operator= (Interconnect const& s);

      private:
      char regulator__;
    };


    class XSC_XML_Handlers_Export Node : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Node, ACE_Null_Mutex> _ptr;

      // name
      public:
      ::XMLSchema::string<ACE_TCHAR> const& name () const;
      void name (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > name_auto_ptr_type;
      name_auto_ptr_type name_;

      // label
      public:
      bool label_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& label () const;
      void label (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > label_auto_ptr_type;
      label_auto_ptr_type label_;

      // connection
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Interconnect, ACE_Null_Mutex> connection_value_type;
      typedef std::list<connection_value_type> connection_container_type;
      typedef connection_container_type::iterator connection_iterator;
      typedef connection_container_type::const_iterator connection_const_iterator;
      connection_iterator begin_connection ();
      connection_iterator end_connection ();
      connection_const_iterator begin_connection () const;
      connection_const_iterator end_connection () const;
      void add_connection (connection_value_type const&);
      size_t count_connection () const;

      protected:
      connection_container_type connection_;

      // sharedResource
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::SharedResource, ACE_Null_Mutex> sharedResource_value_type;
      typedef std::list<sharedResource_value_type> sharedResource_container_type;
      typedef sharedResource_container_type::iterator sharedResource_iterator;
      typedef sharedResource_container_type::const_iterator sharedResource_const_iterator;
      sharedResource_iterator begin_sharedResource ();
      sharedResource_iterator end_sharedResource ();
      sharedResource_const_iterator begin_sharedResource () const;
      sharedResource_const_iterator end_sharedResource () const;
      void add_sharedResource (sharedResource_value_type const&);
      size_t count_sharedResource () const;

      protected:
      sharedResource_container_type sharedResource_;

      // resource
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Resource, ACE_Null_Mutex> resource_value_type;
      typedef std::list<resource_value_type> resource_container_type;
      typedef resource_container_type::iterator resource_iterator;
      typedef resource_container_type::const_iterator resource_const_iterator;
      resource_iterator begin_resource ();
      resource_iterator end_resource ();
      resource_const_iterator begin_resource () const;
      resource_const_iterator end_resource () const;
      void add_resource (resource_value_type const&);
      size_t count_resource () const;

      protected:
      resource_container_type resource_;

      public:
      Node (::XMLSchema::string<ACE_TCHAR> const& name__);

      explicit Node (::XSCRT::XML::Element<ACE_TCHAR> const&);
      Node (Node const& s);
      Node& operator= (Node const& s);

      private:
      char regulator__;
    };


    class XSC_XML_Handlers_Export SharedResource : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::SharedResource, ACE_Null_Mutex> _ptr;

      // name
      public:
      ::XMLSchema::string<ACE_TCHAR> const& name () const;
      void name (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > name_auto_ptr_type;
      name_auto_ptr_type name_;

      // resourceType
      public:
      ::XMLSchema::string<ACE_TCHAR> const& resourceType () const;
      void resourceType (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef std::auto_ptr< ::XMLSchema::string<ACE_TCHAR> > resourceType_auto_ptr_type;
      resourceType_auto_ptr_type resourceType_;

      // node
      public:
      ::DAnCE::Config_Handlers::Node const& node () const;
      void node (::DAnCE::Config_Handlers::Node const& );

      protected:
      typedef std::auto_ptr< ::DAnCE::Config_Handlers::Node > node_auto_ptr_type;
      node_auto_ptr_type node_;

      // property
      public:
      ::DAnCE::Config_Handlers::SatisfierProperty const& property () const;
      void property (::DAnCE::Config_Handlers::SatisfierProperty const& );

      protected:
      typedef std::auto_ptr< ::DAnCE::Config_Handlers::SatisfierProperty > property_auto_ptr_type;
      property_auto_ptr_type property_;

      public:
      SharedResource (::XMLSchema::string<ACE_TCHAR> const& name__,
                      ::XMLSchema::string<ACE_TCHAR> const& resourceType__,
                      ::DAnCE::Config_Handlers::Node const& node__,
                      ::DAnCE::Config_Handlers::SatisfierProperty const& property__);

      explicit SharedResource (::XSCRT::XML::Element<ACE_TCHAR> const&);
      SharedResource (SharedResource const& s);
      SharedResource& operator= (SharedResource const& s);

      private:
      char regulator__;
    };
  }
}

namespace DAnCE
{
  namespace Config_Handlers
  {
  }
}

#include "ace/XML_Utils/XMLSchema/Traversal.hpp"

namespace DAnCE
{
  namespace Config_Handlers
  {
    namespace Traversal
    {
      struct XSC_XML_Handlers_Export Domain : ::XMLSchema::Traversal::Traverser< ::DAnCE::Config_Handlers::Domain >
      {
        virtual void
        traverse (Type&);

        virtual void
        traverse (Type const&);

        virtual void
        pre (Type&);

        virtual void
        pre (Type const&);

        virtual void
        UUID (Type&);

        virtual void
        UUID (Type const&);

        virtual void
        UUID_none (Type&);

        virtual void
        UUID_none (Type const&);

        virtual void
        label (Type&);

        virtual void
        label (Type const&);

        virtual void
        label_none (Type&);

        virtual void
        label_none (Type const&);

        virtual void
        node (Type&);

        virtual void
        node (Type const&);

        virtual void
        node_pre (Type&);

        virtual void
        node_pre (Type const&);

        virtual void
        node_next (Type&);

        virtual void
        node_next (Type const&);

        virtual void
        node_post (Type&);

        virtual void
        node_post (Type const&);

        virtual void
        interconnect (Type&);

        virtual void
        interconnect (Type const&);

        virtual void
        interconnect_pre (Type&);

        virtual void
        interconnect_pre (Type const&);

        virtual void
        interconnect_next (Type&);

        virtual void
        interconnect_next (Type const&);

        virtual void
        interconnect_post (Type&);

        virtual void
        interconnect_post (Type const&);

        virtual void
        interconnect_none (Type&);

        virtual void
        interconnect_none (Type const&);

        virtual void
        bridge (Type&);

        virtual void
        bridge (Type const&);

        virtual void
        bridge_pre (Type&);

        virtual void
        bridge_pre (Type const&);

        virtual void
        bridge_next (Type&);

        virtual void
        bridge_next (Type const&);

        virtual void
        bridge_post (Type&);

        virtual void
        bridge_post (Type const&);

        virtual void
        bridge_none (Type&);

        virtual void
        bridge_none (Type const&);

        virtual void
        sharedResource (Type&);

        virtual void
        sharedResource (Type const&);

        virtual void
        sharedResource_pre (Type&);

        virtual void
        sharedResource_pre (Type const&);

        virtual void
        sharedResource_next (Type&);

        virtual void
        sharedResource_next (Type const&);

        virtual void
        sharedResource_post (Type&);

        virtual void
        sharedResource_post (Type const&);

        virtual void
        sharedResource_none (Type&);

        virtual void
        sharedResource_none (Type const&);

        virtual void
        infoProperty (Type&);

        virtual void
        infoProperty (Type const&);

        virtual void
        infoProperty_pre (Type&);

        virtual void
        infoProperty_pre (Type const&);

        virtual void
        infoProperty_next (Type&);

        virtual void
        infoProperty_next (Type const&);

        virtual void
        infoProperty_post (Type&);

        virtual void
        infoProperty_post (Type const&);

        virtual void
        infoProperty_none (Type&);

        virtual void
        infoProperty_none (Type const&);

        virtual void
        post (Type&);

        virtual void
        post (Type const&);
      };

      struct XSC_XML_Handlers_Export Bridge : ::XMLSchema::Traversal::Traverser< ::DAnCE::Config_Handlers::Bridge >
      {
        virtual void
        traverse (Type&);

        virtual void
        traverse (Type const&);

        virtual void
        pre (Type&);

        virtual void
        pre (Type const&);

        virtual void
        name (Type&);

        virtual void
        name (Type const&);

        virtual void
        label (Type&);

        virtual void
        label (Type const&);

        virtual void
        label_none (Type&);

        virtual void
        label_none (Type const&);

        virtual void
        connect (Type&);

        virtual void
        connect (Type const&);

        virtual void
        connect_pre (Type&);

        virtual void
        connect_pre (Type const&);

        virtual void
        connect_next (Type&);

        virtual void
        connect_next (Type const&);

        virtual void
        connect_post (Type&);

        virtual void
        connect_post (Type const&);

        virtual void
        resource (Type&);

        virtual void
        resource (Type const&);

        virtual void
        resource_pre (Type&);

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type&);

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type&);

        virtual void
        resource_post (Type const&);

        virtual void
        resource_none (Type&);

        virtual void
        resource_none (Type const&);

        virtual void
        post (Type&);

        virtual void
        post (Type const&);
      };

      struct XSC_XML_Handlers_Export Interconnect : ::XMLSchema::Traversal::Traverser< ::DAnCE::Config_Handlers::Interconnect >
      {
        virtual void
        traverse (Type&);

        virtual void
        traverse (Type const&);

        virtual void
        pre (Type&);

        virtual void
        pre (Type const&);

        virtual void
        name (Type&);

        virtual void
        name (Type const&);

        virtual void
        label (Type&);

        virtual void
        label (Type const&);

        virtual void
        label_none (Type&);

        virtual void
        label_none (Type const&);

        virtual void
        connection (Type&);

        virtual void
        connection (Type const&);

        virtual void
        connection_pre (Type&);

        virtual void
        connection_pre (Type const&);

        virtual void
        connection_next (Type&);

        virtual void
        connection_next (Type const&);

        virtual void
        connection_post (Type&);

        virtual void
        connection_post (Type const&);

        virtual void
        connection_none (Type&);

        virtual void
        connection_none (Type const&);

        virtual void
        connect (Type&);

        virtual void
        connect (Type const&);

        virtual void
        connect_pre (Type&);

        virtual void
        connect_pre (Type const&);

        virtual void
        connect_next (Type&);

        virtual void
        connect_next (Type const&);

        virtual void
        connect_post (Type&);

        virtual void
        connect_post (Type const&);

        virtual void
        resource (Type&);

        virtual void
        resource (Type const&);

        virtual void
        resource_pre (Type&);

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type&);

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type&);

        virtual void
        resource_post (Type const&);

        virtual void
        resource_none (Type&);

        virtual void
        resource_none (Type const&);

        virtual void
        post (Type&);

        virtual void
        post (Type const&);
      };

      struct XSC_XML_Handlers_Export Node : ::XMLSchema::Traversal::Traverser< ::DAnCE::Config_Handlers::Node >
      {
        virtual void
        traverse (Type&);

        virtual void
        traverse (Type const&);

        virtual void
        pre (Type&);

        virtual void
        pre (Type const&);

        virtual void
        name (Type&);

        virtual void
        name (Type const&);

        virtual void
        label (Type&);

        virtual void
        label (Type const&);

        virtual void
        label_none (Type&);

        virtual void
        label_none (Type const&);

        virtual void
        connection (Type&);

        virtual void
        connection (Type const&);

        virtual void
        connection_pre (Type&);

        virtual void
        connection_pre (Type const&);

        virtual void
        connection_next (Type&);

        virtual void
        connection_next (Type const&);

        virtual void
        connection_post (Type&);

        virtual void
        connection_post (Type const&);

        virtual void
        connection_none (Type&);

        virtual void
        connection_none (Type const&);

        virtual void
        sharedResource (Type&);

        virtual void
        sharedResource (Type const&);

        virtual void
        sharedResource_pre (Type&);

        virtual void
        sharedResource_pre (Type const&);

        virtual void
        sharedResource_next (Type&);

        virtual void
        sharedResource_next (Type const&);

        virtual void
        sharedResource_post (Type&);

        virtual void
        sharedResource_post (Type const&);

        virtual void
        sharedResource_none (Type&);

        virtual void
        sharedResource_none (Type const&);

        virtual void
        resource (Type&);

        virtual void
        resource (Type const&);

        virtual void
        resource_pre (Type&);

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type&);

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type&);

        virtual void
        resource_post (Type const&);

        virtual void
        resource_none (Type&);

        virtual void
        resource_none (Type const&);

        virtual void
        post (Type&);

        virtual void
        post (Type const&);
      };

      struct XSC_XML_Handlers_Export SharedResource : ::XMLSchema::Traversal::Traverser< ::DAnCE::Config_Handlers::SharedResource >
      {
        virtual void
        traverse (Type&);

        virtual void
        traverse (Type const&);

        virtual void
        pre (Type&);

        virtual void
        pre (Type const&);

        virtual void
        name (Type&);

        virtual void
        name (Type const&);

        virtual void
        resourceType (Type&);

        virtual void
        resourceType (Type const&);

        virtual void
        node (Type&);

        virtual void
        node (Type const&);

        virtual void
        property (Type&);

        virtual void
        property (Type const&);

        virtual void
        post (Type&);

        virtual void
        post (Type const&);
      };
    }
  }
}

#include "ace/XML_Utils/XMLSchema/Writer.hpp"

namespace DAnCE
{
  namespace Config_Handlers
  {
    namespace Writer
    {
      struct Domain : Traversal::Domain,
      virtual ::XSCRT::Writer<ACE_TCHAR>
      {
        typedef ::DAnCE::Config_Handlers::Domain Type;
        explicit Domain (::XSCRT::XML::Element<ACE_TCHAR>&);

        virtual void
        traverse (Type &o)
        {
          this->traverse (const_cast <Type const &> (o));
        }

        virtual void
        traverse (Type const&);

        virtual void
        UUID (Type &o)
        {
          this->UUID (const_cast <Type const &> (o));
        }

        virtual void
        UUID (Type const&);

        virtual void
        label (Type &o)
        {
          this->label (const_cast <Type const &> (o));
        }

        virtual void
        label (Type const&);

        virtual void
        node_pre (Type &o)
        {
          this->node_pre (const_cast <Type const &> (o));
        }

        virtual void
        node_pre (Type const&);

        virtual void
        node_next (Type &o)
        {
          this->node_next (const_cast <Type const &> (o));
        }

        virtual void
        node_next (Type const&);

        virtual void
        node_post (Type &o)
        {
          this->node_post (const_cast <Type const &> (o));
        }

        virtual void
        node_post (Type const&);

        virtual void
        interconnect_pre (Type &o)
        {
          this->interconnect_pre (const_cast <Type const &> (o));
        }

        virtual void
        interconnect_pre (Type const&);

        virtual void
        interconnect_next (Type &o)
        {
          this->interconnect_next (const_cast <Type const &> (o));
        }

        virtual void
        interconnect_next (Type const&);

        virtual void
        interconnect_post (Type &o)
        {
          this->interconnect_post (const_cast <Type const &> (o));
        }

        virtual void
        interconnect_post (Type const&);

        virtual void
        bridge_pre (Type &o)
        {
          this->bridge_pre (const_cast <Type const &> (o));
        }

        virtual void
        bridge_pre (Type const&);

        virtual void
        bridge_next (Type &o)
        {
          this->bridge_next (const_cast <Type const &> (o));
        }

        virtual void
        bridge_next (Type const&);

        virtual void
        bridge_post (Type &o)
        {
          this->bridge_post (const_cast <Type const &> (o));
        }

        virtual void
        bridge_post (Type const&);

        virtual void
        sharedResource_pre (Type &o)
        {
          this->sharedResource_pre (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_pre (Type const&);

        virtual void
        sharedResource_next (Type &o)
        {
          this->sharedResource_next (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_next (Type const&);

        virtual void
        sharedResource_post (Type &o)
        {
          this->sharedResource_post (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_post (Type const&);

        virtual void
        infoProperty_pre (Type &o)
        {
          this->infoProperty_pre (const_cast <Type const &> (o));
        }

        virtual void
        infoProperty_pre (Type const&);

        virtual void
        infoProperty_next (Type &o)
        {
          this->infoProperty_next (const_cast <Type const &> (o));
        }

        virtual void
        infoProperty_next (Type const&);

        virtual void
        infoProperty_post (Type &o)
        {
          this->infoProperty_post (const_cast <Type const &> (o));
        }

        virtual void
        infoProperty_post (Type const&);

        protected:
        Domain ();
      };

      struct Bridge : Traversal::Bridge,
      virtual ::XSCRT::Writer<ACE_TCHAR>
      {
        typedef ::DAnCE::Config_Handlers::Bridge Type;
        explicit Bridge (::XSCRT::XML::Element<ACE_TCHAR>&);

        virtual void
        traverse (Type &o)
        {
          this->traverse (const_cast <Type const &> (o));
        }

        virtual void
        traverse (Type const&);

        virtual void
        name (Type &o)
        {
          this->name (const_cast <Type const &> (o));
        }

        virtual void
        name (Type const&);

        virtual void
        label (Type &o)
        {
          this->label (const_cast <Type const &> (o));
        }

        virtual void
        label (Type const&);

        virtual void
        connect_pre (Type &o)
        {
          this->connect_pre (const_cast <Type const &> (o));
        }

        virtual void
        connect_pre (Type const&);

        virtual void
        connect_next (Type &o)
        {
          this->connect_next (const_cast <Type const &> (o));
        }

        virtual void
        connect_next (Type const&);

        virtual void
        connect_post (Type &o)
        {
          this->connect_post (const_cast <Type const &> (o));
        }

        virtual void
        connect_post (Type const&);

        virtual void
        resource_pre (Type &o)
        {
          this->resource_pre (const_cast <Type const &> (o));
        }

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type &o)
        {
          this->resource_next (const_cast <Type const &> (o));
        }

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type &o)
        {
          this->resource_post (const_cast <Type const &> (o));
        }

        virtual void
        resource_post (Type const&);

        protected:
        Bridge ();
      };

      struct Interconnect : Traversal::Interconnect,
      virtual ::XSCRT::Writer<ACE_TCHAR>
      {
        typedef ::DAnCE::Config_Handlers::Interconnect Type;
        explicit Interconnect (::XSCRT::XML::Element<ACE_TCHAR>&);

        virtual void
        traverse (Type &o)
        {
          this->traverse (const_cast <Type const &> (o));
        }

        virtual void
        traverse (Type const&);

        virtual void
        name (Type &o)
        {
          this->name (const_cast <Type const &> (o));
        }

        virtual void
        name (Type const&);

        virtual void
        label (Type &o)
        {
          this->label (const_cast <Type const &> (o));
        }

        virtual void
        label (Type const&);

        virtual void
        connection_pre (Type &o)
        {
          this->connection_pre (const_cast <Type const &> (o));
        }

        virtual void
        connection_pre (Type const&);

        virtual void
        connection_next (Type &o)
        {
          this->connection_next (const_cast <Type const &> (o));
        }

        virtual void
        connection_next (Type const&);

        virtual void
        connection_post (Type &o)
        {
          this->connection_post (const_cast <Type const &> (o));
        }

        virtual void
        connection_post (Type const&);

        virtual void
        connect_pre (Type &o)
        {
          this->connect_pre (const_cast <Type const &> (o));
        }

        virtual void
        connect_pre (Type const&);

        virtual void
        connect_next (Type &o)
        {
          this->connect_next (const_cast <Type const &> (o));
        }

        virtual void
        connect_next (Type const&);

        virtual void
        connect_post (Type &o)
        {
          this->connect_post (const_cast <Type const &> (o));
        }

        virtual void
        connect_post (Type const&);

        virtual void
        resource_pre (Type &o)
        {
          this->resource_pre (const_cast <Type const &> (o));
        }

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type &o)
        {
          this->resource_next (const_cast <Type const &> (o));
        }

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type &o)
        {
          this->resource_post (const_cast <Type const &> (o));
        }

        virtual void
        resource_post (Type const&);

        protected:
        Interconnect ();
      };

      struct Node : Traversal::Node,
      virtual ::XSCRT::Writer<ACE_TCHAR>
      {
        typedef ::DAnCE::Config_Handlers::Node Type;
        explicit Node (::XSCRT::XML::Element<ACE_TCHAR>&);

        virtual void
        traverse (Type &o)
        {
          this->traverse (const_cast <Type const &> (o));
        }

        virtual void
        traverse (Type const&);

        virtual void
        name (Type &o)
        {
          this->name (const_cast <Type const &> (o));
        }

        virtual void
        name (Type const&);

        virtual void
        label (Type &o)
        {
          this->label (const_cast <Type const &> (o));
        }

        virtual void
        label (Type const&);

        virtual void
        connection_pre (Type &o)
        {
          this->connection_pre (const_cast <Type const &> (o));
        }

        virtual void
        connection_pre (Type const&);

        virtual void
        connection_next (Type &o)
        {
          this->connection_next (const_cast <Type const &> (o));
        }

        virtual void
        connection_next (Type const&);

        virtual void
        connection_post (Type &o)
        {
          this->connection_post (const_cast <Type const &> (o));
        }

        virtual void
        connection_post (Type const&);

        virtual void
        sharedResource_pre (Type &o)
        {
          this->sharedResource_pre (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_pre (Type const&);

        virtual void
        sharedResource_next (Type &o)
        {
          this->sharedResource_next (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_next (Type const&);

        virtual void
        sharedResource_post (Type &o)
        {
          this->sharedResource_post (const_cast <Type const &> (o));
        }

        virtual void
        sharedResource_post (Type const&);

        virtual void
        resource_pre (Type &o)
        {
          this->resource_pre (const_cast <Type const &> (o));
        }

        virtual void
        resource_pre (Type const&);

        virtual void
        resource_next (Type &o)
        {
          this->resource_next (const_cast <Type const &> (o));
        }

        virtual void
        resource_next (Type const&);

        virtual void
        resource_post (Type &o)
        {
          this->resource_post (const_cast <Type const &> (o));
        }

        virtual void
        resource_post (Type const&);

        protected:
        Node ();
      };

      struct SharedResource : Traversal::SharedResource,
      virtual ::XSCRT::Writer<ACE_TCHAR>
      {
        typedef ::DAnCE::Config_Handlers::SharedResource Type;
        explicit SharedResource (::XSCRT::XML::Element<ACE_TCHAR>&);

        virtual void
        traverse (Type &o)
        {
          this->traverse (const_cast <Type const &> (o));
        }

        virtual void
        traverse (Type const&);

        virtual void
        name (Type &o)
        {
          this->name (const_cast <Type const &> (o));
        }

        virtual void
        name (Type const&);

        virtual void
        resourceType (Type &o)
        {
          this->resourceType (const_cast <Type const &> (o));
        }

        virtual void
        resourceType (Type const&);

        virtual void
        node (Type &o)
        {
          this->node (const_cast <Type const &> (o));
        }

        virtual void
        node (Type const&);

        virtual void
        property (Type &o)
        {
          this->property (const_cast <Type const &> (o));
        }

        virtual void
        property (Type const&);

        protected:
        SharedResource ();
      };
    }
  }
}

namespace DAnCE
{
  namespace Config_Handlers
  {
  }
}

#endif // CDD_HPP
