/*
 * This code was generated by the XML Schema Compiler.
 *
 * Changes made to this code will most likely be overwritten
 * when the handlers are recompiled.
 *
 * If you find errors or feel that there are bugfixes to be made,
 * please report this to the XSC project at
 * https://github.com/DOCGroup/XSC
 */
#ifndef IAD_HPP
#define IAD_HPP

#include "XSC_XML_Handlers_Export.h"
// Forward declarations.
namespace DAnCE
{
  namespace Config_Handlers
  {
    class NamedImplementationArtifact;
    class ImplementationArtifactDescription;
  }
}

#include <memory>
#include <string>
#include <list>
#include "ace/XML_Utils/XMLSchema/Types.hpp"
#include "ace/XML_Utils/XMLSchema/id_map.hpp"
#include "ace/Refcounted_Auto_Ptr.h"
#include "ace/Null_Mutex.h"
#include "ace/ace_wchar.h"

#if !defined(XML_XSC_SMART_PTR)
# if defined(ACE_HAS_CPP11)
#   define XML_XSC_SMART_PTR(X) std::unique_ptr<X>
# else
#   define XML_XSC_SMART_PTR(X) std::auto_ptr<X>
# endif
#endif

#include "Basic_Deployment_Data.hpp"

namespace DAnCE
{
  namespace Config_Handlers
  {
    class XSC_XML_Handlers_Export NamedImplementationArtifact : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::NamedImplementationArtifact, ACE_Null_Mutex> _ptr;

      // name
      public:
      ::XMLSchema::string<ACE_TCHAR> const& name () const;
      void name (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::XMLSchema::string<ACE_TCHAR> ) name_auto_ptr_type;
      name_auto_ptr_type name_;

      // referencedArtifact
      public:
      ::DAnCE::Config_Handlers::ImplementationArtifactDescription const& referencedArtifact () const;
      void referencedArtifact (::DAnCE::Config_Handlers::ImplementationArtifactDescription const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::DAnCE::Config_Handlers::ImplementationArtifactDescription ) referencedArtifact_auto_ptr_type;
      referencedArtifact_auto_ptr_type referencedArtifact_;

      public:
      NamedImplementationArtifact (::XMLSchema::string<ACE_TCHAR> const& name__,
                                   ::DAnCE::Config_Handlers::ImplementationArtifactDescription const& referencedArtifact__);

      explicit NamedImplementationArtifact (::XSCRT::XML::Element<ACE_TCHAR> const&);
      NamedImplementationArtifact (NamedImplementationArtifact const& s);
      NamedImplementationArtifact& operator= (NamedImplementationArtifact const& s);
    };


    class XSC_XML_Handlers_Export ImplementationArtifactDescription : public ::XSCRT::Type
    {
      typedef ::XSCRT::Type Base;

      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::ImplementationArtifactDescription, ACE_Null_Mutex> _ptr;

      // label
      public:
      bool label_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& label () const;
      void label (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::XMLSchema::string<ACE_TCHAR> ) label_auto_ptr_type;
      label_auto_ptr_type label_;

      // UUID
      public:
      bool UUID_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& UUID () const;
      void UUID (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::XMLSchema::string<ACE_TCHAR> ) UUID_auto_ptr_type;
      UUID_auto_ptr_type UUID_;

      // location
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::XMLSchema::string<ACE_TCHAR>, ACE_Null_Mutex> location_value_type;
      typedef std::list<location_value_type> location_container_type;
      typedef location_container_type::iterator location_iterator;
      typedef location_container_type::const_iterator location_const_iterator;
      location_iterator begin_location ();
      location_iterator end_location ();
      location_const_iterator begin_location () const;
      location_const_iterator end_location () const;
      void add_location (location_value_type const&);
      size_t count_location () const;

      protected:
      location_container_type location_;

      // dependsOn
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::NamedImplementationArtifact, ACE_Null_Mutex> dependsOn_value_type;
      typedef std::list<dependsOn_value_type> dependsOn_container_type;
      typedef dependsOn_container_type::iterator dependsOn_iterator;
      typedef dependsOn_container_type::const_iterator dependsOn_const_iterator;
      dependsOn_iterator begin_dependsOn ();
      dependsOn_iterator end_dependsOn ();
      dependsOn_const_iterator begin_dependsOn () const;
      dependsOn_const_iterator end_dependsOn () const;
      void add_dependsOn (dependsOn_value_type const&);
      size_t count_dependsOn () const;

      protected:
      dependsOn_container_type dependsOn_;

      // execParameter
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Property, ACE_Null_Mutex> execParameter_value_type;
      typedef std::list<execParameter_value_type> execParameter_container_type;
      typedef execParameter_container_type::iterator execParameter_iterator;
      typedef execParameter_container_type::const_iterator execParameter_const_iterator;
      execParameter_iterator begin_execParameter ();
      execParameter_iterator end_execParameter ();
      execParameter_const_iterator begin_execParameter () const;
      execParameter_const_iterator end_execParameter () const;
      void add_execParameter (execParameter_value_type const&);
      size_t count_execParameter () const;

      protected:
      execParameter_container_type execParameter_;

      // infoProperty
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Property, ACE_Null_Mutex> infoProperty_value_type;
      typedef std::list<infoProperty_value_type> infoProperty_container_type;
      typedef infoProperty_container_type::iterator infoProperty_iterator;
      typedef infoProperty_container_type::const_iterator infoProperty_const_iterator;
      infoProperty_iterator begin_infoProperty ();
      infoProperty_iterator end_infoProperty ();
      infoProperty_const_iterator begin_infoProperty () const;
      infoProperty_const_iterator end_infoProperty () const;
      void add_infoProperty (infoProperty_value_type const&);
      size_t count_infoProperty () const;

      protected:
      infoProperty_container_type infoProperty_;

      // deployRequirement
      public:
      typedef ACE_Refcounted_Auto_Ptr < ::DAnCE::Config_Handlers::Requirement, ACE_Null_Mutex> deployRequirement_value_type;
      typedef std::list<deployRequirement_value_type> deployRequirement_container_type;
      typedef deployRequirement_container_type::iterator deployRequirement_iterator;
      typedef deployRequirement_container_type::const_iterator deployRequirement_const_iterator;
      deployRequirement_iterator begin_deployRequirement ();
      deployRequirement_iterator end_deployRequirement ();
      deployRequirement_const_iterator begin_deployRequirement () const;
      deployRequirement_const_iterator end_deployRequirement () const;
      void add_deployRequirement (deployRequirement_value_type const&);
      size_t count_deployRequirement () const;

      protected:
      deployRequirement_container_type deployRequirement_;

      // contentLocation
      public:
      bool contentLocation_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& contentLocation () const;
      void contentLocation (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::XMLSchema::string<ACE_TCHAR> ) contentLocation_auto_ptr_type;
      contentLocation_auto_ptr_type contentLocation_;

      // href
      public:
      bool href_p () const;
      ::XMLSchema::string<ACE_TCHAR> const& href () const;
      ::XMLSchema::string<ACE_TCHAR>& href ();
      void href (::XMLSchema::string<ACE_TCHAR> const& );

      protected:
      typedef XML_XSC_SMART_PTR( ::XMLSchema::string<ACE_TCHAR> ) href_auto_ptr_type;
      href_auto_ptr_type href_;

      public:
      ImplementationArtifactDescription ();

      explicit ImplementationArtifactDescription (::XSCRT::XML::Element<ACE_TCHAR> const&);
      ImplementationArtifactDescription (ImplementationArtifactDescription const& s);
      ImplementationArtifactDescription& operator= (ImplementationArtifactDescription const& s);
    };
  }
}

namespace DAnCE
{
  namespace Config_Handlers
  {
  }
}

#endif // IAD_HPP
